window.baseMockUsers = [
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" },
    { uid: "-", account: "-", realName: "-", nickname: "-", agentId: "-", inviter: "-", registerMode: "-", phone: "-", payLevel: "-", growth: "-", level: "-", accountType: "-", userType: "-", inviteCode: "-", directTeam: "-", vipLevel: "-", vipGrowth: "-", creditValue: "-", availableCredit: "-", commissionBal: "-", balanceBuy: "-", arrears: "-", interest: "-", thirdBal: "-", points: "-", deposit: "-", withdraw: "-", withdrawPre: "-", adminDeduct: "-", depositCount: "-", withdrawCount: "-", tags: [], status: "-", date: "-", lastLogin: "-", offlineDays: "-", ip: "-", remark: "-", followRemark: "-", note: "-" }
];
